### ISSUE TITLE
Checklist to publish Apple-Find-Me on IoBroker Repo

### ISSUE THREAD

**Issue by PfisterDaniel** [PfisterDaniel/ioBroker.apple-find-me#7]
Feedback from Apollon77:

- [x] Please fix tests .. they are red - i thinl you need to commit the package-lock.json also; also update testing lib, else will also fail: https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/master/package.json#L31

- [x] Hint: You can remove all that manual encrypt/decrypt code if you use the automatic handling which exists since js-controller 3 and admin 4.0.9+ ... see readme of this readme. But works also zthe way you did it for now

- [x] Please consider to change from node_schedule to an interval or better timeout (https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/master/main.js#L586). The reason is that when doing this the start time of the adapter defines the interval which spreads calls over time better then a hard schedule that runs on second 0 on the given minutes (by default every 5 minutes ... for all users of the adapter ... this can generate request peaks and can give issues (even if the servers are the ones from Apple :-) )

- [x] Please remember if objects were already created and do not usse "setObjectNotExists" every x mins ... this is just unneeded database load

- [x] https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/530cd05d94e3c2c4d03696318a63b521967ec8aa/main.js#L160-L174 such constructs will generate warn messages on first object creations because you execute the setState before the objects exists (because created async. So eigther do setState in callback or use asyn/await please

- [x] please check the roles of your states for better options (e.g. value.battery or value.gps.latitude ...) https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md ; also please store dates better as role date (see also state riole page for specs)

- [x] unload MUST stop the schedule! https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/530cd05d94e3c2c4d03696318a63b521967ec8aa/main.js#L47

- [x] please remove https://github.com/PfisterDaniel/ioBroker.apple-find-me/blob/530cd05d94e3c2c4d03696318a63b521967ec8aa/main.js#L62-L70 if not needed

**Comment by PfisterDaniel** [comment]
All Fixed
